remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
repository: open-simulation-platform/cse-core
title: "Core Simulation Environment"
description: "co-simulation software"

plugins:
  - jekyll-include-cache
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji