remote_theme: pmarsceill/just-the-docs
repository: open-simulation-platform/cse-core
logo: "/assets/img/Logo.png"
title: "Open Simulation Platform"
footer_content: "Copyright &copy; Open Simulation Platform."
description: "co-simulation software"
search_enabled: true